name: Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # daily
  push: { branches: ["master", "main"] }

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Main metrics (private-inclusive)
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_READ_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          use_prebuilt_image: yes
          plugins_errors_fatal: no

          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_twemoji: yes
          config_timezone: Europe/Bucharest

          # Languages plugin
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_limit: 12
          plugin_languages_indepth: yes
          plugin_languages_details: percentage, bytes-size, lines
          plugin_languages_skipped: PopaBiancaStefana/Apartment-Explorer-AR-app

          # “Recently used” tuning
          plugin_languages_recent_load: 600
          plugin_languages_recent_days: 30

          # Code plugin
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public

          # Repositories plugin
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random

          # Calendar plugin
          plugin_calendar: yes
          plugin_calendar_limit: 4

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_activity: no # currently broken
          plugin_contributors: no # currently broken

          # Wakatime plugin
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_user: current

          plugin_habits: no # currently broken
          plugin_achievements: no  # currently broken

          # Notable plugin
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit

          # People plugin
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following

          # Topics plugin
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars

          # Stars plugin
          plugin_stars: yes
          plugin_stars_limit: 4

          filename: github-metrics.svg

      # - name: Skyline
      #   uses: lowlighter/metrics@master
      #   with:
      #     token: ${{ secrets.METRICS_READ_TOKEN }}
      #     committer_token: ${{ secrets.GITHUB_TOKEN }}

      #     use_prebuilt_image: yes
      #     plugin_skyline_compatibility: yes
      #     plugins_errors_fatal: no

      #     user: ${{ github.repository_owner }}
      #     base: ""
      #     plugin_skyline: yes
      #     plugin_skyline_year: 2025
      #     plugin_skyline_frames: 60
      #     plugin_skyline_quality: 0.5
      #     filename: metrics-skyline.svg
