name: Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # daily

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Main metrics (private-inclusive)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_READ_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, repositories, metadata
          config_twemoji: yes

          plugin_languages: yes
          plugin_languages_ignored: 0
          plugin_languages_details: percentage

          # Code plugin
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public

          # Repositories plugin
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random

          # Isometric calendar
          plugin_isocalendar: yes
          plugin_calendar_limit: 3
          plugin_isocalendar_duration: full-year
  
          # Activity plugin
          plugin_activity: yes
          plugin_activity_days: 100
          plugin_activity_filter: all
          plugin_activity_limit: 10
          plugin_activity_load: 300
          plugin_activity_visibility: all
    
          # Contributors plugin
          plugin_contributors: yes
          plugin_contributors_contributions: yes

          # Habits (charts + facts)
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Europe/Bucharest

          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # Notable plugin
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit

          # People plugin
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following

          filename: github-metrics.svg

      - name: Skyline
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_READ_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2025
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5
          filename: metrics-skyline.svg
